permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Paranoid Qian
  email: paranoid_qian@163.com
  #link: http://painterlin.com
  #weibo: http://weibo.com/orangeissweet
  github: http://github.com/paranoidq
  #music: http://site.douban.com/linanya
  #linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: Paranoid Qian's Blog
#description: My personal blog
#url: http://painterlin.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/favicon.jpg
favicon: /public/img/favicon.jpg

# google analytics 设置
#ga:
  #id: UA-54262064-1 
  #url: painterlin.com

# disqus 设置
disqus:
  shortname: paranoidq

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
